name: Excavator
on:
  schedule:
    - cron: '25 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  excavate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
